export const hotelsData = [
  {
    hotel: "Sunrise City Hotel",
    location: "Lisbon, Portugal",
    contact: "Front desk manager",
    email: "frontdesk@blueoceanresort.com",
  },
  {
    hotel: "Blue Ocean Resort",
    location: "Barcelona, Spain",
    contact: "Ana Silva",
    email: "ana@sunrisecityhotel.pt",
  },
  {
    hotel: "Blue Ocean Resort",
    location: "Barcelona, Spain",
    contact: "Owner",
    email: "info@airportstayinn.gr",
  },
  {
    hotel: "Blue Ocean Resort",
    location: "Barcelona, Spain",
    contact: "Manager",
    email: "owner@oldtownhostel.cz",
  },
  {
    hotel: "Grand Plaza Hotel",
    location: "Madrid, Spain",
    contact: "Carlos Rodriguez",
    email: "carlos@grandplaza.com",
  },
  {
    hotel: "Mountain View Inn",
    location: "Zurich, Switzerland",
    contact: "Thomas Muller",
    email: "thomas@mountainview.ch",
  },
  {
    hotel: "Royal Palace Hotel",
    location: "Vienna, Austria",
    contact: "Sophie Weber",
    email: "sophie@royalpalace.at",
  },
  {
    hotel: "Seaside Resort",
    location: "Nice, France",
    contact: "Pierre Dubois",
    email: "pierre@seasideresort.fr",
  },
  {
    hotel: "City Center Hotel",
    location: "Berlin, Germany",
    contact: "Hans Schmidt",
    email: "hans@citycenter.de",
  },
  {
    hotel: "Garden Oasis Hotel",
    location: "Rome, Italy",
    contact: "Giuseppe Romano",
    email: "giuseppe@gardenoasis.it",
  },
  {
    hotel: "Luxury Suites",
    location: "Paris, France",
    contact: "Marie Laurent",
    email: "marie@luxurysuites.fr",
  },
  {
    hotel: "Business Tower Hotel",
    location: "London, UK",
    contact: "James Wilson",
    email: "james@businesstower.co.uk",
  },
  {
    hotel: "Sunset Beach Resort",
    location: "Athens, Greece",
    contact: "Dimitrios Papadopoulos",
    email: "dimitrios@sunsetbeach.gr",
  },
  {
    hotel: "Downtown Inn",
    location: "Amsterdam, Netherlands",
    contact: "Lars van Dijk",
    email: "lars@downtowninn.nl",
  },
  {
    hotel: "Harbor View Hotel",
    location: "Stockholm, Sweden",
    email: "frontdesk@harborview.se",
  },
  {
    hotel: "Executive Stay",
    location: "Brussels, Belgium",
    contact: "Emma Martin",
    email: "emma@executivestay.be",
  },
  {
    hotel: "Riverside Hotel",
    location: "Prague, Czech Republic",
    contact: "Petr Novak",
    email: "petr@riverside.cz",
  },
  {
    hotel: "Metropolitan Hotel",
    location: "Budapest, Hungary",
    contact: "Istvan Kovacs",
    email: "istvan@metropolitan.hu",
  },
  {
    hotel: "Skyline Towers",
    location: "Warsaw, Poland",
    contact: "Anna Nowak",
    email: "anna@skylinetowers.pl",
  },
  {
    hotel: "Paradise Resort",
    location: "Dubrovnik, Croatia",
    contact: "Ivan Horvat",
    email: "ivan@paradiseresort.hr",
  },
  {
    hotel: "Crystal Bay Hotel",
    location: "Oslo, Norway",
    contact: "Erik Johansen",
    email: "erik@crystalbay.no",
  },
  {
    hotel: "Urban Retreat",
    location: "Copenhagen, Denmark",
    contact: "Lars Nielsen",
    email: "lars@urbanretreat.dk",
  },
  {
    hotel: "Alpine Lodge",
    location: "Innsbruck, Austria",
    contact: "Franz Huber",
    email: "franz@alpinelodge.at",
  },
  {
    hotel: "Coastal Haven",
    location: "Porto, Portugal",
    contact: "Miguel Santos",
    email: "miguel@coastalhaven.pt",
  },
  {
    hotel: "Historic Grand Hotel",
    location: "Edinburgh, Scotland",
    contact: "Robert MacLeod",
    email: "robert@historicgrand.co.uk",
  },
  {
    hotel: "Modern Suites",
    location: "Helsinki, Finland",
    contact: "Mika Virtanen",
    email: "mika@modernsuites.fi",
  },
  {
    hotel: "Boutique Hotel",
    location: "Dublin, Ireland",
    contact: "Sean O'Connor",
    email: "sean@boutiquehotel.ie",
  },
  {
    hotel: "Lakeside Resort",
    location: "Geneva, Switzerland",
    contact: "Claude Moreau",
    email: "claude@lakeside.ch",
  },
  {
    hotel: "City Lights Hotel",
    location: "Milan, Italy",
    contact: "Marco Rossi",
    email: "marco@citylights.it",
  },
  {
    hotel: "Garden View Inn",
    location: "Lyon, France",
    contact: "Camille Bernard",
    email: "camille@gardenview.fr",
  },
  {
    hotel: "Business Class Hotel",
    location: "Frankfurt, Germany",
    contact: "Klaus Fischer",
    email: "klaus@businessclass.de",
  },
  {
    hotel: "Seaview Resort",
    location: "Malaga, Spain",
    contact: "Juan Garcia",
    email: "juan@seaview.es",
  },
  {
    hotel: "Mountain Retreat",
    location: "Salzburg, Austria",
    contact: "Monika Bauer",
    email: "monika@mountainretreat.at",
  },
  {
    hotel: "Urban Loft Hotel",
    location: "Hamburg, Germany",
    contact: "Sabine Wagner",
    email: "sabine@urbanloft.de",
  },
  {
    hotel: "Royal Garden Hotel",
    location: "Brussels, Belgium",
    contact: "Jean Dupont",
    email: "jean@royalgarden.be",
  },
  {
    hotel: "Sunrise Suites",
    location: "Lisbon, Portugal",
    contact: "Isabel Costa",
    email: "isabel@sunsuites.pt",
  },
  {
    hotel: "Ocean Breeze Resort",
    location: "Valencia, Spain",
    contact: "Maria Lopez",
    email: "maria@oceanbreeze.es",
  },
  {
    hotel: "City Gate Hotel",
    location: "Rotterdam, Netherlands",
    contact: "Peter de Vries",
    email: "peter@citygate.nl",
  },
  {
    hotel: "Grand Central Hotel",
    location: "Munich, Germany",
    contact: "Stefan Hoffmann",
    email: "stefan@grandcentral.de",
  },
  {
    hotel: "Parkside Inn",
    location: "Copenhagen, Denmark",
    contact: "Karen Madsen",
    email: "karen@parkside.dk",
  },
];
