export const lostItemsData2 = [
  {
    id: "01",
    itemNo: "01",
    item: "Black laptop bag",
    description: '15" bag with red zipper',
    foundLocation: "Room 504",
    foundDate: "21/02/2025",
    guest: "Maria Ahmed",
    contact: "maria21@gmail.com",
    roomReservation: "Ahmed 504",
    checkoutDate: "20/02/2025",
    status: "Email sent",
  },
  {
    id: "02",
    itemNo: "02",
    item: "Black laptop bag",
    description: '15" bag with red zipper',
    foundLocation: "Room 504",
    foundDate: "21/02/2025",
    guest: "Maria Ahmed",
    contact: "maria21@gmail.com",
    roomReservation: "Ahmed 504",
    checkoutDate: "20/02/2025",
    status: "Email sent",
  },
  {
    id: "03",
    itemNo: "03",
    item: "iPhone 14 Pro",
    description: "Space black, 128GB",
    foundLocation: "Lobby",
    foundDate: "22/02/2025",
    guest: "John Smith",
    contact: "john.smith@email.com",
    roomReservation: "Smith 301",
    checkoutDate: "21/02/2025",
    status: "Not claimed",
  },
  {
    id: "04",
    itemNo: "04",
    item: "Wallet",
    description: "Brown leather, contains ID cards",
    foundLocation: "Restaurant",
    foundDate: "20/02/2025",
    guest: "Sarah Johnson",
    contact: "sarah.j@email.com",
    roomReservation: "Johnson 205",
    checkoutDate: "19/02/2025",
    status: "Claimed",
  },
  {
    id: "05",
    itemNo: "05",
    item: "Sunglasses",
    description: "Ray-Ban aviator, gold frame",
    foundLocation: "Pool area",
    foundDate: "23/02/2025",
    guest: "Mike Wilson",
    contact: "mike.wilson@email.com",
    roomReservation: "Wilson 412",
    checkoutDate: "22/02/2025",
    status: "Email sent",
  },
  {
    id: "06",
    itemNo: "06",
    item: "Watch",
    description: "Rolex Submariner, black dial",
    foundLocation: "Gym",
    foundDate: "19/02/2025",
    guest: "David Brown",
    contact: "david.b@email.com",
    roomReservation: "Brown 108",
    checkoutDate: "18/02/2025",
    status: "Not claimed",
  },
  {
    id: "07",
    itemNo: "07",
    item: "Camera",
    description: "Canon EOS R5 with lens",
    foundLocation: "Conference room",
    foundDate: "24/02/2025",
    guest: "Emma Davis",
    contact: "emma.davis@email.com",
    roomReservation: "Davis 309",
    checkoutDate: "23/02/2025",
    status: "Email sent",
  },
  {
    id: "08",
    itemNo: "08",
    item: "Backpack",
    description: "North Face, blue color",
    foundLocation: "Parking lot",
    foundDate: "18/02/2025",
    guest: "Robert Taylor",
    contact: "robert.t@email.com",
    roomReservation: "Taylor 201",
    checkoutDate: "17/02/2025",
    status: "Claimed",
  },
  {
    id: "09",
    itemNo: "09",
    item: "Jewelry box",
    description: "Small wooden box with necklace",
    foundLocation: "Room 107",
    foundDate: "25/02/2025",
    guest: "Lisa Anderson",
    contact: "lisa.a@email.com",
    roomReservation: "Anderson 107",
    checkoutDate: "24/02/2025",
    status: "Not claimed",
  },
  {
    id: "10",
    itemNo: "10",
    item: "Passport",
    description: "US passport, John Doe",
    foundLocation: "Reception",
    foundDate: "17/02/2025",
    guest: "John Doe",
    contact: "john.doe@email.com",
    roomReservation: "Doe 105",
    checkoutDate: "16/02/2025",
    status: "Claimed",
  },
  {
    id: "11",
    itemNo: "11",
    item: "Laptop",
    description: 'MacBook Pro 16", space gray',
    foundLocation: "Business center",
    foundDate: "26/02/2025",
    guest: "Alex Turner",
    contact: "alex.t@email.com",
    roomReservation: "Turner 408",
    checkoutDate: "25/02/2025",
    status: "Email sent",
  },
  {
    id: "12",
    itemNo: "12",
    item: "Keys",
    description: "Keychain with car keys",
    foundLocation: "Elevator",
    foundDate: "16/02/2025",
    guest: "Sophia Martinez",
    contact: "sophia.m@email.com",
    roomReservation: "Martinez 203",
    checkoutDate: "15/02/2025",
    status: "Claimed",
  },

  // ---------- GENERATED BELOW (13–40) ----------

  {
    id: "13",
    itemNo: "13",
    item: "Tablet",
    description: "Samsung Galaxy Tab S8",
    foundLocation: "Lobby sofa",
    foundDate: "26/02/2025",
    guest: "Henry Lee",
    contact: "henry.lee@email.com",
    roomReservation: "Lee 302",
    checkoutDate: "25/02/2025",
    status: "Not claimed",
  },
  {
    id: "14",
    itemNo: "14",
    item: "Scarf",
    description: "Red wool scarf",
    foundLocation: "Restaurant",
    foundDate: "27/02/2025",
    guest: "Emily Clark",
    contact: "emily.c@email.com",
    roomReservation: "Clark 214",
    checkoutDate: "26/02/2025",
    status: "Email sent",
  },
  {
    id: "15",
    itemNo: "15",
    item: "Shoes",
    description: "Nike Air Max, size 10",
    foundLocation: "Gym locker room",
    foundDate: "27/02/2025",
    guest: "Brian Adams",
    contact: "b.adams@email.com",
    roomReservation: "Adams 119",
    checkoutDate: "26/02/2025",
    status: "Not claimed",
  },
  {
    id: "16",
    itemNo: "16",
    item: "Necklace",
    description: "Gold chain necklace",
    foundLocation: "Room 601",
    foundDate: "24/02/2025",
    guest: "Hannah White",
    contact: "hannah.w@email.com",
    roomReservation: "White 601",
    checkoutDate: "23/02/2025",
    status: "Claimed",
  },
  {
    id: "17",
    itemNo: "17",
    item: "Earbuds",
    description: "Apple AirPods Pro",
    foundLocation: "Pool lounge",
    foundDate: "25/02/2025",
    guest: "Owen Carter",
    contact: "owen.c@email.com",
    roomReservation: "Carter 507",
    checkoutDate: "24/02/2025",
    status: "Email sent",
  },
  {
    id: "18",
    itemNo: "18",
    item: "Handbag",
    description: "Gucci handbag, black",
    foundLocation: "Lobby",
    foundDate: "27/02/2025",
    guest: "Natalie Ford",
    contact: "natalie.f@email.com",
    roomReservation: "Ford 402",
    checkoutDate: "26/02/2025",
    status: "Not claimed",
  },
  {
    id: "19",
    itemNo: "19",
    item: "Cap",
    description: "Blue Adidas cap",
    foundLocation: "Conference hall",
    foundDate: "24/02/2025",
    guest: "Daniel Evans",
    contact: "dan.ev@email.com",
    roomReservation: "Evans 311",
    checkoutDate: "23/02/2025",
    status: "Email sent",
  },
  {
    id: "20",
    itemNo: "20",
    item: "Power bank",
    description: "Anker 20,000mAh",
    foundLocation: "Reception",
    foundDate: "23/02/2025",
    guest: "Claire Miller",
    contact: "claire.m@email.com",
    roomReservation: "Miller 210",
    checkoutDate: "22/02/2025",
    status: "Claimed",
  },
  {
    id: "21",
    itemNo: "21",
    item: "Hair straightener",
    description: "Dyson Corrale",
    foundLocation: "Room 402",
    foundDate: "26/02/2025",
    guest: "Amelia Ross",
    contact: "amelia.r@email.com",
    roomReservation: "Ross 402",
    checkoutDate: "25/02/2025",
    status: "Email sent",
  },
  {
    id: "22",
    itemNo: "22",
    item: "Book",
    description: '"Atomic Habits" by James Clear',
    foundLocation: "Lobby table",
    foundDate: "22/02/2025",
    guest: "George Harris",
    contact: "george.h@email.com",
    roomReservation: "Harris 218",
    checkoutDate: "21/02/2025",
    status: "Not claimed",
  },
  {
    id: "23",
    itemNo: "23",
    item: "Perfume",
    description: "Chanel No.5",
    foundLocation: "Restaurant washroom",
    foundDate: "20/02/2025",
    guest: "Isabella King",
    contact: "isabella.k@email.com",
    roomReservation: "King 509",
    checkoutDate: "19/02/2025",
    status: "Claimed",
  },
  {
    id: "24",
    itemNo: "24",
    item: "Jacket",
    description: "Leather jacket, black",
    foundLocation: "Lobby coat stand",
    foundDate: "21/02/2025",
    guest: "Liam Scott",
    contact: "liam.s@email.com",
    roomReservation: "Scott 310",
    checkoutDate: "20/02/2025",
    status: "Email sent",
  },
  {
    id: "25",
    itemNo: "25",
    item: "Bracelet",
    description: "Silver bracelet with stones",
    foundLocation: "Room 209",
    foundDate: "23/02/2025",
    guest: "Chloe Green",
    contact: "chloe.g@email.com",
    roomReservation: "Green 209",
    checkoutDate: "22/02/2025",
    status: "Not claimed",
  },
  {
    id: "26",
    itemNo: "26",
    item: "Sweater",
    description: "Grey wool sweater",
    foundLocation: "Restaurant chair",
    foundDate: "24/02/2025",
    guest: "Ethan Lee",
    contact: "ethan.l@email.com",
    roomReservation: "Lee 112",
    checkoutDate: "23/02/2025",
    status: "Email sent",
  },
  {
    id: "27",
    itemNo: "27",
    item: "Belt",
    description: "Brown leather belt",
    foundLocation: "Gym",
    foundDate: "26/02/2025",
    guest: "Jack Turner",
    contact: "jack.t@email.com",
    roomReservation: "Turner 415",
    checkoutDate: "25/02/2025",
    status: "Claimed",
  },
  {
    id: "28",
    itemNo: "28",
    item: "Notebook",
    description: "Black diary with notes",
    foundLocation: "Business center",
    foundDate: "27/02/2025",
    guest: "Mia Parker",
    contact: "mia.p@email.com",
    roomReservation: "Parker 508",
    checkoutDate: "26/02/2025",
    status: "Not claimed",
  },
  {
    id: "29",
    itemNo: "29",
    item: "Charger",
    description: "Apple USB-C charger",
    foundLocation: "Room 318",
    foundDate: "22/02/2025",
    guest: "Oliver Baker",
    contact: "oliver.b@email.com",
    roomReservation: "Baker 318",
    checkoutDate: "21/02/2025",
    status: "Email sent",
  },
  {
    id: "30",
    itemNo: "30",
    item: "Bag",
    description: "Small brown pouch",
    foundLocation: "Spa area",
    foundDate: "23/02/2025",
    guest: "Ella Brooks",
    contact: "ella.b@email.com",
    roomReservation: "Brooks 221",
    checkoutDate: "22/02/2025",
    status: "Claimed",
  },
  {
    id: "31",
    itemNo: "31",
    item: "Gloves",
    description: "Black winter gloves",
    foundLocation: "Parking lot",
    foundDate: "25/02/2025",
    guest: "Mason Hill",
    contact: "mason.h@email.com",
    roomReservation: "Hill 102",
    checkoutDate: "24/02/2025",
    status: "Not claimed",
  },
  {
    id: "32",
    itemNo: "32",
    item: "Hat",
    description: "White cotton hat",
    foundLocation: "Pool bar",
    foundDate: "26/02/2025",
    guest: "Lily Cooper",
    contact: "lily.c@email.com",
    roomReservation: "Cooper 420",
    checkoutDate: "25/02/2025",
    status: "Email sent",
  },
  {
    id: "33",
    itemNo: "33",
    item: "Ring",
    description: "Gold ring with diamond",
    foundLocation: "Room 507",
    foundDate: "21/02/2025",
    guest: "Ava Morgan",
    contact: "ava.m@email.com",
    roomReservation: "Morgan 507",
    checkoutDate: "20/02/2025",
    status: "Claimed",
  },
  {
    id: "34",
    itemNo: "34",
    item: "Towel",
    description: "White spa towel",
    foundLocation: "Spa locker",
    foundDate: "22/02/2025",
    guest: "Noah Fisher",
    contact: "noah.f@email.com",
    roomReservation: "Fisher 313",
    checkoutDate: "21/02/2025",
    status: "Not claimed",
  },
  {
    id: "35",
    itemNo: "35",
    item: "Headphones",
    description: "Sony WH-1000XM5",
    foundLocation: "Conference lobby",
    foundDate: "24/02/2025",
    guest: "Isla Reed",
    contact: "isla.r@email.com",
    roomReservation: "Reed 510",
    checkoutDate: "23/02/2025",
    status: "Email sent",
  },
  {
    id: "36",
    itemNo: "36",
    item: "Cosmetic pouch",
    description: "Pink pouch with makeup items",
    foundLocation: "Room 404",
    foundDate: "26/02/2025",
    guest: "Zoe Walker",
    contact: "zoe.w@email.com",
    roomReservation: "Walker 404",
    checkoutDate: "25/02/2025",
    status: "Claimed",
  },
  {
    id: "37",
    itemNo: "37",
    item: "Travel adapter",
    description: "Universal travel adapter",
    foundLocation: "Reception counter",
    foundDate: "27/02/2025",
    guest: "Evan Cook",
    contact: "evan.c@email.com",
    roomReservation: "Cook 217",
    checkoutDate: "26/02/2025",
    status: "Not claimed",
  },
  {
    id: "38",
    itemNo: "38",
    item: "Pen",
    description: "Montblanc black pen",
    foundLocation: "Conference table",
    foundDate: "25/02/2025",
    guest: "Harper Lewis",
    contact: "harper.l@email.com",
    roomReservation: "Lewis 311",
    checkoutDate: "24/02/2025",
    status: "Email sent",
  },
  {
    id: "39",
    itemNo: "39",
    item: "Water bottle",
    description: "Black metal flask",
    foundLocation: "Gym rack",
    foundDate: "23/02/2025",
    guest: "Nathan Wood",
    contact: "nathan.w@email.com",
    roomReservation: "Wood 109",
    checkoutDate: "22/02/2025",
    status: "Not claimed",
  },
  {
    id: "40",
    itemNo: "40",
    item: "Toy",
    description: "Small teddy bear",
    foundLocation: "Lobby sofa",
    foundDate: "21/02/2025",
    guest: "Olivia Young",
    contact: "olivia.y@email.com",
    roomReservation: "Young 215",
    checkoutDate: "20/02/2025",
    status: "Claimed",
  },
];
