export const lostItemsData = [
  {
    itemId: "LFI-0231",
    itemName: "Black Laptop Bag",
    hotel: "Blue Ocean Resort",
    location: "Barcelona, Spain",
    foundLocation: "Room 504",
    foundDate: "21/03/2025",
    category: "Electronics",
    status: "Awaiting Guest Payment",
  },
  {
    itemId: "LFI-0232",
    itemName: "iPhone 15 Pro",
    hotel: "Sunrise City Hotel",
    location: "Lisbon, Portugal",
    foundLocation: "Lobby",
    foundDate: "20/03/2025",
    category: "Electronics",
    status: "Contacting Guest",
  },
  {
    itemId: "LFI-0233",
    itemName: "Gold Watch",
    hotel: "Grand Plaza Hotel",
    location: "Madrid, Spain",
    foundLocation: "Restaurant",
    foundDate: "19/03/2025",
    category: "Jewelry",
    status: "Verified Owner",
  },
  {
    itemId: "LFI-0234",
    itemName: "Passport - John Smith",
    hotel: "Mountain View Inn",
    location: "Zurich, Switzerland",
    foundLocation: "Reception",
    foundDate: "18/03/2025",
    category: "Documents",
    status: "Urgent - Contacting",
  },
  {
    itemId: "LFI-0235",
    itemName: "Sunglasses",
    hotel: "Royal Palace Hotel",
    location: "Vienna, Austria",
    foundLocation: "Pool Area",
    foundDate: "17/03/2025",
    category: "Accessories",
    status: "In Storage",
  },
  {
    itemId: "LFI-0236",
    itemName: "Wallet with Cards",
    hotel: "Seaside Resort",
    location: "Nice, France",
    foundLocation: "Beach Bar",
    foundDate: "16/03/2025",
    category: "Personal Items",
    status: "Owner Found",
  },
  {
    itemId: "LFI-0237",
    itemName: "Camera Canon EOS",
    hotel: "City Center Hotel",
    location: "Berlin, Germany",
    foundLocation: "Conference Room",
    foundDate: "15/03/2025",
    category: "Electronics",
    status: "Awaiting Guest Payment",
  },
  {
    itemId: "LFI-0238",
    itemName: "Backpack",
    hotel: "Garden Oasis Hotel",
    location: "Rome, Italy",
    foundLocation: "Garden",
    foundDate: "14/03/2025",
    category: "Bags",
    status: "Unclaimed",
  },
  {
    itemId: "LFI-0239",
    itemName: "AirPods Pro",
    hotel: "Luxury Suites",
    location: "Paris, France",
    foundLocation: "Spa",
    foundDate: "13/03/2025",
    category: "Electronics",
    status: "Contacting Guest",
  },
  {
    itemId: "LFI-0240",
    itemName: "Wedding Ring",
    hotel: "Business Tower Hotel",
    location: "London, UK",
    foundLocation: "Wedding Hall",
    foundDate: "12/03/2025",
    category: "Jewelry",
    status: "Urgent - Contacting",
  },

  {
    itemId: "LFI-0241",
    itemName: "Tablet Samsung Galaxy",
    hotel: "Seaside Palace",
    location: "Barcelona, Spain",
    foundLocation: "Lobby",
    foundDate: "11/03/2025",
    category: "Electronics",
    status: "In Storage",
  },
  {
    itemId: "LFI-0242",
    itemName: "Diamond Necklace",
    hotel: "Grand Beach Hotel",
    location: "Lisbon, Portugal",
    foundLocation: "Room 302",
    foundDate: "10/03/2025",
    category: "Jewelry",
    status: "Owner Found",
  },
  {
    itemId: "LFI-0243",
    itemName: "Driver's License - Emma Brown",
    hotel: "City Lights Inn",
    location: "Madrid, Spain",
    foundLocation: "Reception",
    foundDate: "09/03/2025",
    category: "Documents",
    status: "Contacting Guest",
  },
  {
    itemId: "LFI-0244",
    itemName: "Leather Jacket",
    hotel: "Royal Garden Hotel",
    location: "Zurich, Switzerland",
    foundLocation: "Closet",
    foundDate: "08/03/2025",
    category: "Clothing",
    status: "Unclaimed",
  },
  {
    itemId: "LFI-0245",
    itemName: "Fitness Tracker",
    hotel: "Mountain Resort",
    location: "Vienna, Austria",
    foundLocation: "Gym",
    foundDate: "07/03/2025",
    category: "Electronics",
    status: "Awaiting Guest Payment",
  },
  {
    itemId: "LFI-0246",
    itemName: "Cash Wallet",
    hotel: "Sunset Boulevard Hotel",
    location: "Nice, France",
    foundLocation: "Lobby",
    foundDate: "06/03/2025",
    category: "Personal Items",
    status: "Verified Owner",
  },
  {
    itemId: "LFI-0247",
    itemName: "Canon Lens",
    hotel: "City Center Suites",
    location: "Berlin, Germany",
    foundLocation: "Conference Room",
    foundDate: "05/03/2025",
    category: "Electronics",
    status: "In Storage",
  },
  {
    itemId: "LFI-0248",
    itemName: "Travel Backpack",
    hotel: "Garden Hotel",
    location: "Rome, Italy",
    foundLocation: "Garden",
    foundDate: "04/03/2025",
    category: "Bags",
    status: "Contacting Guest",
  },
  {
    itemId: "LFI-0249",
    itemName: "iPad Pro",
    hotel: "Luxury Resort",
    location: "Paris, France",
    foundLocation: "Spa",
    foundDate: "03/03/2025",
    category: "Electronics",
    status: "Awaiting Guest Payment",
  },
  {
    itemId: "LFI-0250",
    itemName: "Gold Earrings",
    hotel: "Business Hotel",
    location: "London, UK",
    foundLocation: "Reception",
    foundDate: "02/03/2025",
    category: "Jewelry",
    status: "Owner Found",
  },

  {
    itemId: "LFI-0251",
    itemName: "Passport - Alice Green",
    hotel: "Blue Ocean Resort",
    location: "Barcelona, Spain",
    foundLocation: "Room 101",
    foundDate: "01/03/2025",
    category: "Documents",
    status: "Urgent - Contacting",
  },
  {
    itemId: "LFI-0252",
    itemName: "Sunglasses Ray-Ban",
    hotel: "Sunrise City Hotel",
    location: "Lisbon, Portugal",
    foundLocation: "Lobby",
    foundDate: "28/02/2025",
    category: "Accessories",
    status: "In Storage",
  },
  {
    itemId: "LFI-0253",
    itemName: "iPhone Charger",
    hotel: "Grand Plaza Hotel",
    location: "Madrid, Spain",
    foundLocation: "Room 208",
    foundDate: "27/02/2025",
    category: "Electronics",
    status: "Unclaimed",
  },
  {
    itemId: "LFI-0254",
    itemName: "Wedding Bracelet",
    hotel: "Mountain View Inn",
    location: "Zurich, Switzerland",
    foundLocation: "Reception",
    foundDate: "26/02/2025",
    category: "Jewelry",
    status: "Contacting Guest",
  },
  {
    itemId: "LFI-0255",
    itemName: "Sports Shoes",
    hotel: "Royal Palace Hotel",
    location: "Vienna, Austria",
    foundLocation: "Gym",
    foundDate: "25/02/2025",
    category: "Clothing",
    status: "In Storage",
  },
  {
    itemId: "LFI-0256",
    itemName: "Wallet - Michael Lee",
    hotel: "Seaside Resort",
    location: "Nice, France",
    foundLocation: "Beach Bar",
    foundDate: "24/02/2025",
    category: "Personal Items",
    status: "Owner Found",
  },
  {
    itemId: "LFI-0257",
    itemName: "Camera Nikon D750",
    hotel: "City Center Hotel",
    location: "Berlin, Germany",
    foundLocation: "Conference Room",
    foundDate: "23/02/2025",
    category: "Electronics",
    status: "Awaiting Guest Payment",
  },
  {
    itemId: "LFI-0258",
    itemName: "School Backpack",
    hotel: "Garden Oasis Hotel",
    location: "Rome, Italy",
    foundLocation: "Garden",
    foundDate: "22/02/2025",
    category: "Bags",
    status: "Unclaimed",
  },
  {
    itemId: "LFI-0259",
    itemName: "AirPods Max",
    hotel: "Luxury Suites",
    location: "Paris, France",
    foundLocation: "Spa",
    foundDate: "21/02/2025",
    category: "Electronics",
    status: "Contacting Guest",
  },
  {
    itemId: "LFI-0260",
    itemName: "Wedding Ring Set",
    hotel: "Business Tower Hotel",
    location: "London, UK",
    foundLocation: "Wedding Hall",
    foundDate: "20/02/2025",
    category: "Jewelry",
    status: "Urgent - Contacting",
  },

  {
    itemId: "LFI-0261",
    itemName: "Kindle Paperwhite",
    hotel: "Seaside Palace",
    location: "Barcelona, Spain",
    foundLocation: "Lobby",
    foundDate: "19/02/2025",
    category: "Electronics",
    status: "In Storage",
  },
  {
    itemId: "LFI-0262",
    itemName: "Silver Bracelet",
    hotel: "Grand Beach Hotel",
    location: "Lisbon, Portugal",
    foundLocation: "Room 302",
    foundDate: "18/02/2025",
    category: "Jewelry",
    status: "Owner Found",
  },
  {
    itemId: "LFI-0263",
    itemName: "ID Card - Tom Harris",
    hotel: "City Lights Inn",
    location: "Madrid, Spain",
    foundLocation: "Reception",
    foundDate: "17/02/2025",
    category: "Documents",
    status: "Contacting Guest",
  },
  {
    itemId: "LFI-0264",
    itemName: "Winter Coat",
    hotel: "Royal Garden Hotel",
    location: "Zurich, Switzerland",
    foundLocation: "Closet",
    foundDate: "16/02/2025",
    category: "Clothing",
    status: "Unclaimed",
  },
  {
    itemId: "LFI-0265",
    itemName: "Smart Watch",
    hotel: "Mountain Resort",
    location: "Vienna, Austria",
    foundLocation: "Gym",
    foundDate: "15/02/2025",
    category: "Electronics",
    status: "Awaiting Guest Payment",
  },
  {
    itemId: "LFI-0266",
    itemName: "Money Bag",
    hotel: "Sunset Boulevard Hotel",
    location: "Nice, France",
    foundLocation: "Lobby",
    foundDate: "14/02/2025",
    category: "Personal Items",
    status: "Verified Owner",
  },
  {
    itemId: "LFI-0267",
    itemName: "GoPro Hero 12",
    hotel: "City Center Suites",
    location: "Berlin, Germany",
    foundLocation: "Conference Room",
    foundDate: "13/02/2025",
    category: "Electronics",
    status: "In Storage",
  },
  {
    itemId: "LFI-0268",
    itemName: "Travel Duffle Bag",
    hotel: "Garden Hotel",
    location: "Rome, Italy",
    foundLocation: "Garden",
    foundDate: "12/02/2025",
    category: "Bags",
    status: "Contacting Guest",
  },
  {
    itemId: "LFI-0269",
    itemName: "MacBook Air",
    hotel: "Luxury Resort",
    location: "Paris, France",
    foundLocation: "Spa",
    foundDate: "11/02/2025",
    category: "Electronics",
    status: "Awaiting Guest Payment",
  },
  {
    itemId: "LFI-0270",
    itemName: "Platinum Ring",
    hotel: "Business Hotel",
    location: "London, UK",
    foundLocation: "Reception",
    foundDate: "10/02/2025",
    category: "Jewelry",
    status: "Owner Found",
  },
];
