export const ordersData = [
  {
    orderId: "LFI-0231",
    guest: "Maria Ahmed",
    hotel: "Blue Ocean Resort",
    createdOn: "20/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €32 · Tax: €4",
    totalAmount: "€45",
  },
  {
    orderId: "LFI-0232",
    guest: "John Smith",
    hotel: "Sunrise City Hotel",
    createdOn: "19/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €28 · Tax: €3",
    totalAmount: "€40",
  },
  {
    orderId: "LFI-0233",
    guest: "Sarah Chen",
    hotel: "Grand Plaza Hotel",
    createdOn: "18/03/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €35 · Tax: €4",
    totalAmount: "€48",
  },
  {
    orderId: "LFI-0234",
    guest: "David Wilson",
    hotel: "Mountain View Inn",
    createdOn: "17/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €30 · Tax: €3",
    totalAmount: "€42",
  },
  {
    orderId: "LFI-0235",
    guest: "Emma Brown",
    hotel: "Royal Palace Hotel",
    createdOn: "16/03/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €25 · Tax: €3",
    totalAmount: "€37",
  },

  {
    orderId: "LFI-0236",
    guest: "Michael Lee",
    hotel: "Seaside Resort",
    createdOn: "15/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €34 · Tax: €4",
    totalAmount: "€47",
  },
  {
    orderId: "LFI-0237",
    guest: "Olivia Martin",
    hotel: "City Center Hotel",
    createdOn: "14/03/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €29 · Tax: €3",
    totalAmount: "€41",
  },
  {
    orderId: "LFI-0238",
    guest: "Liam Johnson",
    hotel: "Garden Oasis Hotel",
    createdOn: "13/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €31 · Tax: €3",
    totalAmount: "€43",
  },
  {
    orderId: "LFI-0239",
    guest: "Sophia Wang",
    hotel: "Luxury Suites",
    createdOn: "12/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €33 · Tax: €4",
    totalAmount: "€46",
  },
  {
    orderId: "LFI-0240",
    guest: "James Taylor",
    hotel: "Business Tower Hotel",
    createdOn: "11/03/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €27 · Tax: €3",
    totalAmount: "€39",
  },

  {
    orderId: "LFI-0241",
    guest: "Isabella Clark",
    hotel: "Blue Ocean Resort",
    createdOn: "10/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €32 · Tax: €4",
    totalAmount: "€45",
  },
  {
    orderId: "LFI-0242",
    guest: "Ethan Davis",
    hotel: "Sunrise City Hotel",
    createdOn: "09/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €30 · Tax: €3",
    totalAmount: "€42",
  },
  {
    orderId: "LFI-0243",
    guest: "Mia Wilson",
    hotel: "Grand Plaza Hotel",
    createdOn: "08/03/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €28 · Tax: €3",
    totalAmount: "€40",
  },
  {
    orderId: "LFI-0244",
    guest: "Noah Anderson",
    hotel: "Mountain View Inn",
    createdOn: "07/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €35 · Tax: €4",
    totalAmount: "€48",
  },
  {
    orderId: "LFI-0245",
    guest: "Ava Martinez",
    hotel: "Royal Palace Hotel",
    createdOn: "06/03/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €26 · Tax: €3",
    totalAmount: "€38",
  },

  {
    orderId: "LFI-0246",
    guest: "William Lee",
    hotel: "Seaside Resort",
    createdOn: "05/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €33 · Tax: €4",
    totalAmount: "€46",
  },
  {
    orderId: "LFI-0247",
    guest: "Emily Robinson",
    hotel: "City Center Hotel",
    createdOn: "04/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €29 · Tax: €3",
    totalAmount: "€41",
  },
  {
    orderId: "LFI-0248",
    guest: "Alexander Thomas",
    hotel: "Garden Oasis Hotel",
    createdOn: "03/03/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €31 · Tax: €3",
    totalAmount: "€43",
  },
  {
    orderId: "LFI-0249",
    guest: "Charlotte White",
    hotel: "Luxury Suites",
    createdOn: "02/03/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €34 · Tax: €4",
    totalAmount: "€47",
  },
  {
    orderId: "LFI-0250",
    guest: "Benjamin Harris",
    hotel: "Business Tower Hotel",
    createdOn: "01/03/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €27 · Tax: €3",
    totalAmount: "€39",
  },

  {
    orderId: "LFI-0251",
    guest: "Amelia Lewis",
    hotel: "Blue Ocean Resort",
    createdOn: "28/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €30 · Tax: €3",
    totalAmount: "€42",
  },
  {
    orderId: "LFI-0252",
    guest: "Daniel Walker",
    hotel: "Sunrise City Hotel",
    createdOn: "27/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €33 · Tax: €4",
    totalAmount: "€46",
  },
  {
    orderId: "LFI-0253",
    guest: "Grace Hall",
    hotel: "Grand Plaza Hotel",
    createdOn: "26/02/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €28 · Tax: €3",
    totalAmount: "€40",
  },
  {
    orderId: "LFI-0254",
    guest: "Lucas Allen",
    hotel: "Mountain View Inn",
    createdOn: "25/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €32 · Tax: €4",
    totalAmount: "€45",
  },
  {
    orderId: "LFI-0255",
    guest: "Ella Young",
    hotel: "Royal Palace Hotel",
    createdOn: "24/02/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €26 · Tax: €3",
    totalAmount: "€38",
  },

  {
    orderId: "LFI-0256",
    guest: "Henry King",
    hotel: "Seaside Resort",
    createdOn: "23/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €35 · Tax: €4",
    totalAmount: "€48",
  },
  {
    orderId: "LFI-0257",
    guest: "Lily Scott",
    hotel: "City Center Hotel",
    createdOn: "22/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €31 · Tax: €3",
    totalAmount: "€43",
  },
  {
    orderId: "LFI-0258",
    guest: "Matthew Adams",
    hotel: "Garden Oasis Hotel",
    createdOn: "21/02/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €29 · Tax: €3",
    totalAmount: "€41",
  },
  {
    orderId: "LFI-0259",
    guest: "Zoe Baker",
    hotel: "Luxury Suites",
    createdOn: "20/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €34 · Tax: €4",
    totalAmount: "€47",
  },
  {
    orderId: "LFI-0260",
    guest: "Jack Carter",
    hotel: "Business Tower Hotel",
    createdOn: "19/02/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €27 · Tax: €3",
    totalAmount: "€39",
  },
  {
    orderId: "LFI-0261",
    guest: "Chloe Evans",
    hotel: "Blue Ocean Resort",
    createdOn: "18/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €33 · Tax: €4",
    totalAmount: "€46",
  },
  {
    orderId: "LFI-0262",
    guest: "Ryan Moore",
    hotel: "Sunrise City Hotel",
    createdOn: "17/02/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €28 · Tax: €3",
    totalAmount: "€40",
  },
  {
    orderId: "LFI-0263",
    guest: "Hannah Thompson",
    hotel: "Grand Plaza Hotel",
    createdOn: "16/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €31 · Tax: €3",
    totalAmount: "€43",
  },
  {
    orderId: "LFI-0264",
    guest: "Owen Harris",
    hotel: "Mountain View Inn",
    createdOn: "15/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €34 · Tax: €4",
    totalAmount: "€47",
  },
  {
    orderId: "LFI-0265",
    guest: "Avery Martin",
    hotel: "Royal Palace Hotel",
    createdOn: "14/02/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €26 · Tax: €3",
    totalAmount: "€38",
  },
  {
    orderId: "LFI-0266",
    guest: "Leo Jackson",
    hotel: "Seaside Resort",
    createdOn: "13/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €32 · Tax: €4",
    totalAmount: "€45",
  },
  {
    orderId: "LFI-0267",
    guest: "Sofia Lewis",
    hotel: "City Center Hotel",
    createdOn: "12/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €30 · Tax: €3",
    totalAmount: "€42",
  },
  {
    orderId: "LFI-0268",
    guest: "Ethan Walker",
    hotel: "Garden Oasis Hotel",
    createdOn: "11/02/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "DHL",
    priceBreakdown: "Service: €9 · Shipping: €29 · Tax: €3",
    totalAmount: "€41",
  },
  {
    orderId: "LFI-0269",
    guest: "Lily King",
    hotel: "Luxury Suites",
    createdOn: "10/02/2025",
    paymentStatus: "Paid",
    shippingLabel: "Label generated",
    courier: "FedEx",
    priceBreakdown: "Service: €9 · Shipping: €33 · Tax: €4",
    totalAmount: "€46",
  },
  {
    orderId: "LFI-0270",
    guest: "Mason Scott",
    hotel: "Business Tower Hotel",
    createdOn: "09/02/2025",
    paymentStatus: "Awaiting payment",
    shippingLabel: "Cancelled",
    courier: "UPS",
    priceBreakdown: "Service: €9 · Shipping: €27 · Tax: €3",
    totalAmount: "€39",
  },
];
