export const recentOrders = [
  {
    orderId: "#ORD-001",
    guest: "Sarah Chen",
    hotel: "Sunrise City Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-002",
    guest: "Michael Rodriguez",
    hotel: "Grand Plaza Hotel",
    status: "Pending",
  },
  {
    orderId: "#ORD-003",
    guest: "Emma Wilson",
    hotel: "Blue Ocean Resort",
    status: "In transit",
  },
  {
    orderId: "#ORD-004",
    guest: "James Thompson",
    hotel: "Mountain View Inn",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-005",
    guest: "Olivia Parker",
    hotel: "Royal Palace Hotel",
    status: "Pending",
  },
  {
    orderId: "#ORD-006",
    guest: "Daniel Kim",
    hotel: "Seaside Resort",
    status: "In transit",
  },
  {
    orderId: "#ORD-007",
    guest: "Sophia Martinez",
    hotel: "City Center Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-008",
    guest: "Ethan Johnson",
    hotel: "Garden Oasis Hotel",
    status: "Pending",
  },
  {
    orderId: "#ORD-009",
    guest: "Isabella Brown",
    hotel: "Luxury Suites",
    status: "In transit",
  },
  {
    orderId: "#ORD-010",
    guest: "Alexander Davis",
    hotel: "Business Tower Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-011",
    guest: "Mia Garcia",
    hotel: "Sunset Beach Resort",
    status: "Pending",
  },
  {
    orderId: "#ORD-012",
    guest: "William Lee",
    hotel: "Downtown Inn",
    status: "In transit",
  },
  {
    orderId: "#ORD-013",
    guest: "Charlotte White",
    hotel: "Harbor View Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-014",
    guest: "Benjamin Clark",
    hotel: "Executive Stay",
    status: "Pending",
  },
  {
    orderId: "#ORD-015",
    guest: "Amelia Hall",
    hotel: "Riverside Hotel",
    status: "In transit",
  },
  {
    orderId: "#ORD-016",
    guest: "Lucas Scott",
    hotel: "Metropolitan Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-017",
    guest: "Harper Young",
    hotel: "Skyline Towers",
    status: "Pending",
  },
  {
    orderId: "#ORD-018",
    guest: "Henry King",
    hotel: "Paradise Resort",
    status: "In transit",
  },
  {
    orderId: "#ORD-019",
    guest: "Evelyn Green",
    hotel: "Crystal Bay Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-020",
    guest: "Jack Adams",
    hotel: "Urban Retreat",
    status: "Pending",
  },
  {
    orderId: "#ORD-021",
    guest: "Luna Hernandez",
    hotel: "Sunrise City Hotel",
    status: "In transit",
  },
  {
    orderId: "#ORD-022",
    guest: "Owen Nelson",
    hotel: "Grand Plaza Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-023",
    guest: "Aria Carter",
    hotel: "Blue Ocean Resort",
    status: "Pending",
  },
  {
    orderId: "#ORD-024",
    guest: "Leo Mitchell",
    hotel: "Mountain View Inn",
    status: "In transit",
  },
  {
    orderId: "#ORD-025",
    guest: "Lily Perez",
    hotel: "Royal Palace Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-026",
    guest: "Mason Roberts",
    hotel: "Seaside Resort",
    status: "Pending",
  },
  {
    orderId: "#ORD-027",
    guest: "Grace Turner",
    hotel: "City Center Hotel",
    status: "In transit",
  },
  {
    orderId: "#ORD-028",
    guest: "Logan Phillips",
    hotel: "Garden Oasis Hotel",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-029",
    guest: "Zoe Campbell",
    hotel: "Luxury Suites",
    status: "Pending",
  },
  {
    orderId: "#ORD-030",
    guest: "Carter Evans",
    hotel: "Business Tower Hotel",
    status: "In transit",
  },
  {
    orderId: "#ORD-031",
    guest: "Nora Edwards",
    hotel: "Sunset Beach Resort",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-032",
    guest: "Jayden Collins",
    hotel: "Downtown Inn",
    status: "Pending",
  },
  {
    orderId: "#ORD-033",
    guest: "Hazel Stewart",
    hotel: "Harbor View Hotel",
    status: "In transit",
  },
  {
    orderId: "#ORD-034",
    guest: "Gabriel Sanchez",
    hotel: "Executive Stay",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-035",
    guest: "Ellie Morris",
    hotel: "Riverside Hotel",
    status: "Pending",
  },
  {
    orderId: "#ORD-036",
    guest: "Julian Rogers",
    hotel: "Metropolitan Hotel",
    status: "In transit",
  },
  {
    orderId: "#ORD-037",
    guest: "Stella Reed",
    hotel: "Skyline Towers",
    status: "Confirmed",
  },
  {
    orderId: "#ORD-038",
    guest: "Wyatt Cook",
    hotel: "Paradise Resort",
    status: "Pending",
  },
  {
    orderId: "#ORD-039",
    guest: "Violet Morgan",
    hotel: "Crystal Bay Hotel",
    status: "In transit",
  },
  {
    orderId: "#ORD-040",
    guest: "Nathan Bell",
    hotel: "Urban Retreat",
    status: "Confirmed",
  },
];
