export const reviewsData = [
  {
    id: "1",
    userName: "John Smith",
    userEmail: "john.smith@email.com",
    rating: 5,
    comment:
      "Excellent service! My lost laptop was returned within 24 hours. Very professional and efficient.",
    hotel: "Grand Plaza Hotel",
    roomNumber: "304",
    date: "2024-01-15",
    status: "Published",
  },
  {
    id: "2",
    userName: "Sarah Johnson",
    userEmail: "sarah.j@email.com",
    rating: 4,
    comment:
      "Good service but took a bit longer than expected. Staff was very helpful though.",
    hotel: "Ocean View Resort",
    roomNumber: "512",
    date: "2024-01-14",
    status: "Published",
  },
  {
    id: "3",
    userName: "Mike Wilson",
    userEmail: "mike.wilson@email.com",
    rating: 3,
    comment:
      "Average experience. My item was found but communication could be better.",
    hotel: "City Center Hotel",
    roomNumber: "208",
    date: "2024-01-13",
    status: "Pending",
  },
  {
    id: "4",
    userName: "Emma Davis",
    userEmail: "emma.davis@email.com",
    rating: 5,
    comment:
      "Outstanding service! They found my wedding ring and shipped it to me securely. Forever grateful!",
    hotel: "Luxury Suites",
    roomNumber: "701",
    date: "2024-01-12",
    status: "Published",
  },
  {
    id: "5",
    userName: "Robert Taylor",
    userEmail: "robert.t@email.com",
    rating: 2,
    comment:
      "Disappointed with the service. Lost my jacket and it took over a week to get any update.",
    hotel: "Business Inn",
    roomNumber: "105",
    date: "2024-01-11",
    status: "Rejected",
  },
  {
    id: "6",
    userName: "Lisa Anderson",
    userEmail: "lisa.a@email.com",
    rating: 4,
    comment:
      "Pretty good service. Found my passport quickly and the process was smooth.",
    hotel: "Airport Hotel",
    roomNumber: "309",
    date: "2024-01-10",
    status: "Published",
  },
  {
    id: "7",
    userName: "David Brown",
    userEmail: "david.b@email.com",
    rating: 5,
    comment:
      "Amazing team! They found my expensive camera and handled it with care. Highly recommended!",
    hotel: "Mountain Resort",
    roomNumber: "412",
    date: "2024-01-09",
    status: "Published",
  },
  {
    id: "8",
    userName: "Sophia Martinez",
    userEmail: "sophia.m@email.com",
    rating: 1,
    comment:
      "Very poor service. My item was damaged when returned and no compensation was offered.",
    hotel: "Beachfront Hotel",
    roomNumber: "204",
    date: "2024-01-08",
    status: "Rejected",
  },

  // ------------ NEW STARTS HERE (IDs 9 - 40) ------------

  {
    id: "9",
    userName: "Chris Evans",
    userEmail: "chris.evans@email.com",
    rating: 5,
    comment:
      "Super fast response. Impressed with how they handled my lost watch.",
    hotel: "Grand Plaza Hotel",
    roomNumber: "418",
    date: "2024-01-07",
    status: "Published",
  },
  {
    id: "10",
    userName: "Hannah Lee",
    userEmail: "hannah.lee@email.com",
    rating: 4,
    comment: "Good service overall. Would appreciate quicker updates.",
    hotel: "Skyline Tower",
    roomNumber: "602",
    date: "2024-01-06",
    status: "Published",
  },
  {
    id: "11",
    userName: "James Carter",
    userEmail: "james.c@email.com",
    rating: 3,
    comment: "Item was found but returned late.",
    hotel: "Royal Heritage Hotel",
    roomNumber: "122",
    date: "2024-01-05",
    status: "Pending",
  },
  {
    id: "12",
    userName: "Olivia Thomas",
    userEmail: "olivia.t@email.com",
    rating: 5,
    comment: "Amazing! They recovered my lost camera lens.",
    hotel: "Luxury Suites",
    roomNumber: "803",
    date: "2024-01-04",
    status: "Published",
  },
  {
    id: "13",
    userName: "Ethan Walker",
    userEmail: "ethan.w@email.com",
    rating: 2,
    comment: "Not satisfied. Took too long to get an answer.",
    hotel: "Ocean View Resort",
    roomNumber: "514",
    date: "2024-01-03",
    status: "Rejected",
  },
  {
    id: "14",
    userName: "Ava Harris",
    userEmail: "ava.h@email.com",
    rating: 4,
    comment: "Good experience! Staff was friendly.",
    hotel: "City Center Hotel",
    roomNumber: "312",
    date: "2024-01-02",
    status: "Published",
  },
  {
    id: "15",
    userName: "Mason Jones",
    userEmail: "mason.j@email.com",
    rating: 5,
    comment: "They found my diamond bracelet! Excellent service.",
    hotel: "Royal Crown Hotel",
    roomNumber: "221",
    date: "2024-01-01",
    status: "Published",
  },
  {
    id: "16",
    userName: "Mia White",
    userEmail: "mia.w@email.com",
    rating: 3,
    comment: "Response time needs improvement.",
    hotel: "Mountain Resort",
    roomNumber: "405",
    date: "2023-12-30",
    status: "Pending",
  },
  {
    id: "17",
    userName: "Noah Clark",
    userEmail: "noah.c@email.com",
    rating: 4,
    comment: "Helpful team. They found my earbuds quickly.",
    hotel: "Skyline Tower",
    roomNumber: "509",
    date: "2023-12-29",
    status: "Published",
  },
  {
    id: "18",
    userName: "Isabella Lewis",
    userEmail: "isabella.l@email.com",
    rating: 5,
    comment: "Outstanding support and communication.",
    hotel: "Luxury Suites",
    roomNumber: "719",
    date: "2023-12-28",
    status: "Published",
  },
  {
    id: "19",
    userName: "Liam Perez",
    userEmail: "liam.p@email.com",
    rating: 1,
    comment: "Terrible experience. They lost my reported item.",
    hotel: "Business Inn",
    roomNumber: "107",
    date: "2023-12-27",
    status: "Rejected",
  },
  {
    id: "20",
    userName: "Emily King",
    userEmail: "emily.k@email.com",
    rating: 5,
    comment: "Very friendly service! Got my purse back the same day.",
    hotel: "Grand Plaza Hotel",
    roomNumber: "504",
    date: "2023-12-26",
    status: "Published",
  },
  {
    id: "21",
    userName: "Jacob Scott",
    userEmail: "jacob.s@email.com",
    rating: 4,
    comment: "Good communication throughout the process.",
    hotel: "Ocean View Resort",
    roomNumber: "311",
    date: "2023-12-25",
    status: "Published",
  },
  {
    id: "22",
    userName: "Grace Hall",
    userEmail: "grace.h@email.com",
    rating: 2,
    comment: "Item was damaged. Not happy.",
    hotel: "City Center Hotel",
    roomNumber: "221",
    date: "2023-12-24",
    status: "Rejected",
  },
  {
    id: "23",
    userName: "Lucas Green",
    userEmail: "lucas.g@email.com",
    rating: 5,
    comment: "Perfect! My wallet was found and delivered fast.",
    hotel: "Beachfront Hotel",
    roomNumber: "118",
    date: "2023-12-23",
    status: "Published",
  },
  {
    id: "24",
    userName: "Chloe Adams",
    userEmail: "chloe.a@email.com",
    rating: 3,
    comment: "Average service. Could be better.",
    hotel: "Airport Hotel",
    roomNumber: "412",
    date: "2023-12-22",
    status: "Pending",
  },
  {
    id: "25",
    userName: "Daniel Baker",
    userEmail: "daniel.b@email.com",
    rating: 4,
    comment: "Recovered my sunglasses quickly.",
    hotel: "Grand Plaza Hotel",
    roomNumber: "623",
    date: "2023-12-21",
    status: "Published",
  },
  {
    id: "26",
    userName: "Zoe Mitchell",
    userEmail: "zoe.m@email.com",
    rating: 5,
    comment: "Exceptional service!",
    hotel: "Royal Crown Hotel",
    roomNumber: "320",
    date: "2023-12-20",
    status: "Published",
  },
  {
    id: "27",
    userName: "Henry Roberts",
    userEmail: "henry.r@email.com",
    rating: 2,
    comment: "Found late. Not satisfied.",
    hotel: "Business Inn",
    roomNumber: "106",
    date: "2023-12-19",
    status: "Rejected",
  },
  {
    id: "28",
    userName: "Sofia Turner",
    userEmail: "sofia.t@email.com",
    rating: 4,
    comment: "Helpful team, professional behavior.",
    hotel: "Luxury Suites",
    roomNumber: "910",
    date: "2023-12-18",
    status: "Published",
  },
  {
    id: "29",
    userName: "Logan Hill",
    userEmail: "logan.h@email.com",
    rating: 3,
    comment: "Fine, nothing special.",
    hotel: "Mountain Resort",
    roomNumber: "308",
    date: "2023-12-17",
    status: "Pending",
  },
  {
    id: "30",
    userName: "Aria Campbell",
    userEmail: "aria.c@email.com",
    rating: 5,
    comment: "They saved my trip by finding my passport!",
    hotel: "Airport Hotel",
    roomNumber: "212",
    date: "2023-12-16",
    status: "Published",
  },
  {
    id: "31",
    userName: "Wyatt Rivera",
    userEmail: "wyatt.r@email.com",
    rating: 4,
    comment: "Smooth process.",
    hotel: "Ocean View Resort",
    roomNumber: "401",
    date: "2023-12-15",
    status: "Published",
  },
  {
    id: "32",
    userName: "Ella Cooper",
    userEmail: "ella.c@email.com",
    rating: 5,
    comment: "Fantastic support!",
    hotel: "Skyline Tower",
    roomNumber: "514",
    date: "2023-12-14",
    status: "Published",
  },
  {
    id: "33",
    userName: "Jack Ramirez",
    userEmail: "jack.r@email.com",
    rating: 1,
    comment: "Very slow and unhelpful.",
    hotel: "City Center Hotel",
    roomNumber: "102",
    date: "2023-12-13",
    status: "Rejected",
  },
  {
    id: "34",
    userName: "Nora Bailey",
    userEmail: "nora.b@email.com",
    rating: 4,
    comment: "Good team effort.",
    hotel: "Royal Heritage Hotel",
    roomNumber: "223",
    date: "2023-12-12",
    status: "Published",
  },
  {
    id: "35",
    userName: "Eli Foster",
    userEmail: "eli.f@email.com",
    rating: 5,
    comment: "Best lost & found service ever!",
    hotel: "Grand Plaza Hotel",
    roomNumber: "633",
    date: "2023-12-11",
    status: "Published",
  },
  {
    id: "36",
    userName: "Lily Brooks",
    userEmail: "lily.b@email.com",
    rating: 3,
    comment: "Acceptable, but communication was slow.",
    hotel: "Beachfront Hotel",
    roomNumber: "310",
    date: "2023-12-10",
    status: "Pending",
  },
  {
    id: "37",
    userName: "Benjamin Ward",
    userEmail: "benjamin.w@email.com",
    rating: 4,
    comment: "Helpful and polite.",
    hotel: "Business Inn",
    roomNumber: "214",
    date: "2023-12-09",
    status: "Published",
  },
  {
    id: "38",
    userName: "Scarlett Murphy",
    userEmail: "scarlett.m@email.com",
    rating: 5,
    comment: "Amazing! They found my necklace.",
    hotel: "Luxury Suites",
    roomNumber: "802",
    date: "2023-12-08",
    status: "Published",
  },
  {
    id: "39",
    userName: "Dylan Parker",
    userEmail: "dylan.p@email.com",
    rating: 2,
    comment: "Long wait time.",
    hotel: "Airport Hotel",
    roomNumber: "119",
    date: "2023-12-07",
    status: "Rejected",
  },
  {
    id: "40",
    userName: "Victoria Hughes",
    userEmail: "victoria.h@email.com",
    rating: 5,
    comment: "Perfect service. Highly recommend!",
    hotel: "Grand Plaza Hotel",
    roomNumber: "702",
    date: "2023-12-06",
    status: "Published",
  },
];
