export const shipmentsData = [
  {
    orderId: "LFI-0231",
    shipmentId: "SH-4839201",
    guest: "Maria Ahmed",
    hotel: "Blue Ocean Resort",
    courier: "DHL",
    trackingNumber: "DHL-4839201",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0232",
    shipmentId: "SH-4839202",
    guest: "John Smith",
    hotel: "Sunrise City Hotel",
    courier: "UPS",
    trackingNumber: "UPS-5837202",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0233",
    shipmentId: "SH-4839203",
    guest: "Sarah Chen",
    hotel: "Grand Plaza Hotel",
    courier: "DHL",
    trackingNumber: "DHL-6839203",
    labelStatus: "Cancelled",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0234",
    shipmentId: "SH-4839204",
    guest: "David Wilson",
    hotel: "Mountain View Inn",
    courier: "FedEx",
    trackingNumber: "FED-7839204",
    labelStatus: "Label generated",
    shipmentStatus: "Pending",
  },
  {
    orderId: "LFI-0235",
    shipmentId: "SH-4839205",
    guest: "Emma Brown",
    hotel: "Royal Palace Hotel",
    courier: "UPS",
    trackingNumber: "UPS-8839205",
    labelStatus: "Cancelled",
    shipmentStatus: "Cancelled",
  },

  {
    orderId: "LFI-0236",
    shipmentId: "SH-4839206",
    guest: "Michael Lee",
    hotel: "Seaside Resort",
    courier: "DHL",
    trackingNumber: "DHL-9839206",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0237",
    shipmentId: "SH-4839207",
    guest: "Olivia Martin",
    hotel: "City Center Hotel",
    courier: "FedEx",
    trackingNumber: "FED-0839207",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0238",
    shipmentId: "SH-4839208",
    guest: "Liam Johnson",
    hotel: "Garden Oasis Hotel",
    courier: "UPS",
    trackingNumber: "UPS-1839208",
    labelStatus: "Cancelled",
    shipmentStatus: "Pending",
  },
  {
    orderId: "LFI-0239",
    shipmentId: "SH-4839209",
    guest: "Sophia Wang",
    hotel: "Luxury Suites",
    courier: "DHL",
    trackingNumber: "DHL-2839209",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0240",
    shipmentId: "SH-4839210",
    guest: "James Taylor",
    hotel: "Business Tower Hotel",
    courier: "FedEx",
    trackingNumber: "FED-3839210",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },

  {
    orderId: "LFI-0241",
    shipmentId: "SH-4839211",
    guest: "Isabella Clark",
    hotel: "Blue Ocean Resort",
    courier: "UPS",
    trackingNumber: "UPS-4839211",
    labelStatus: "Label generated",
    shipmentStatus: "Pending",
  },
  {
    orderId: "LFI-0242",
    shipmentId: "SH-4839212",
    guest: "Ethan Davis",
    hotel: "Sunrise City Hotel",
    courier: "DHL",
    trackingNumber: "DHL-5839212",
    labelStatus: "Cancelled",
    shipmentStatus: "Cancelled",
  },
  {
    orderId: "LFI-0243",
    shipmentId: "SH-4839213",
    guest: "Mia Wilson",
    hotel: "Grand Plaza Hotel",
    courier: "FedEx",
    trackingNumber: "FED-6839213",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0244",
    shipmentId: "SH-4839214",
    guest: "Noah Anderson",
    hotel: "Mountain View Inn",
    courier: "UPS",
    trackingNumber: "UPS-7839214",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0245",
    shipmentId: "SH-4839215",
    guest: "Ava Martinez",
    hotel: "Royal Palace Hotel",
    courier: "DHL",
    trackingNumber: "DHL-8839215",
    labelStatus: "Cancelled",
    shipmentStatus: "Pending",
  },

  {
    orderId: "LFI-0246",
    shipmentId: "SH-4839216",
    guest: "William Lee",
    hotel: "Seaside Resort",
    courier: "FedEx",
    trackingNumber: "FED-9839216",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0247",
    shipmentId: "SH-4839217",
    guest: "Emily Robinson",
    hotel: "City Center Hotel",
    courier: "UPS",
    trackingNumber: "UPS-0839217",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0248",
    shipmentId: "SH-4839218",
    guest: "Alexander Thomas",
    hotel: "Garden Oasis Hotel",
    courier: "DHL",
    trackingNumber: "DHL-1839218",
    labelStatus: "Cancelled",
    shipmentStatus: "Cancelled",
  },
  {
    orderId: "LFI-0249",
    shipmentId: "SH-4839219",
    guest: "Charlotte White",
    hotel: "Luxury Suites",
    courier: "FedEx",
    trackingNumber: "FED-2839219",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0250",
    shipmentId: "SH-4839220",
    guest: "Benjamin Harris",
    hotel: "Business Tower Hotel",
    courier: "UPS",
    trackingNumber: "UPS-3839220",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },

  {
    orderId: "LFI-0251",
    shipmentId: "SH-4839221",
    guest: "Amelia Lewis",
    hotel: "Blue Ocean Resort",
    courier: "DHL",
    trackingNumber: "DHL-4839221",
    labelStatus: "Cancelled",
    shipmentStatus: "Pending",
  },
  {
    orderId: "LFI-0252",
    shipmentId: "SH-4839222",
    guest: "Daniel Walker",
    hotel: "Sunrise City Hotel",
    courier: "FedEx",
    trackingNumber: "FED-5839222",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0253",
    shipmentId: "SH-4839223",
    guest: "Grace Hall",
    hotel: "Grand Plaza Hotel",
    courier: "UPS",
    trackingNumber: "UPS-6839223",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0254",
    shipmentId: "SH-4839224",
    guest: "Lucas Allen",
    hotel: "Mountain View Inn",
    courier: "DHL",
    trackingNumber: "DHL-7839224",
    labelStatus: "Cancelled",
    shipmentStatus: "Cancelled",
  },
  {
    orderId: "LFI-0255",
    shipmentId: "SH-4839225",
    guest: "Ella Young",
    hotel: "Royal Palace Hotel",
    courier: "FedEx",
    trackingNumber: "FED-8839225",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },

  {
    orderId: "LFI-0256",
    shipmentId: "SH-4839226",
    guest: "Henry King",
    hotel: "Seaside Resort",
    courier: "UPS",
    trackingNumber: "UPS-9839226",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0257",
    shipmentId: "SH-4839227",
    guest: "Lily Scott",
    hotel: "City Center Hotel",
    courier: "DHL",
    trackingNumber: "DHL-0839227",
    labelStatus: "Cancelled",
    shipmentStatus: "Pending",
  },
  {
    orderId: "LFI-0258",
    shipmentId: "SH-4839228",
    guest: "Matthew Adams",
    hotel: "Garden Oasis Hotel",
    courier: "FedEx",
    trackingNumber: "FED-1839228",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0259",
    shipmentId: "SH-4839229",
    guest: "Zoe Baker",
    hotel: "Luxury Suites",
    courier: "UPS",
    trackingNumber: "UPS-2839229",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0260",
    shipmentId: "SH-4839230",
    guest: "Jack Carter",
    hotel: "Business Tower Hotel",
    courier: "DHL",
    trackingNumber: "DHL-3839230",
    labelStatus: "Cancelled",
    shipmentStatus: "Cancelled",
  },

  {
    orderId: "LFI-0261",
    shipmentId: "SH-4839231",
    guest: "Chloe Evans",
    hotel: "Blue Ocean Resort",
    courier: "UPS",
    trackingNumber: "UPS-4839231",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0262",
    shipmentId: "SH-4839232",
    guest: "Ryan Moore",
    hotel: "Sunrise City Hotel",
    courier: "DHL",
    trackingNumber: "DHL-5839232",
    labelStatus: "Cancelled",
    shipmentStatus: "Cancelled",
  },
  {
    orderId: "LFI-0263",
    shipmentId: "SH-4839233",
    guest: "Hannah Thompson",
    hotel: "Grand Plaza Hotel",
    courier: "FedEx",
    trackingNumber: "FED-6839233",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0264",
    shipmentId: "SH-4839234",
    guest: "Owen Harris",
    hotel: "Mountain View Inn",
    courier: "UPS",
    trackingNumber: "UPS-7839234",
    labelStatus: "Label generated",
    shipmentStatus: "Pending",
  },
  {
    orderId: "LFI-0265",
    shipmentId: "SH-4839235",
    guest: "Avery Martin",
    hotel: "Royal Palace Hotel",
    courier: "DHL",
    trackingNumber: "DHL-8839235",
    labelStatus: "Cancelled",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0266",
    shipmentId: "SH-4839236",
    guest: "Leo Jackson",
    hotel: "Seaside Resort",
    courier: "FedEx",
    trackingNumber: "FED-9839236",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0267",
    shipmentId: "SH-4839237",
    guest: "Sofia Lewis",
    hotel: "City Center Hotel",
    courier: "UPS",
    trackingNumber: "UPS-0839237",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
  {
    orderId: "LFI-0268",
    shipmentId: "SH-4839238",
    guest: "Ethan Walker",
    hotel: "Garden Oasis Hotel",
    courier: "DHL",
    trackingNumber: "DHL-1839238",
    labelStatus: "Cancelled",
    shipmentStatus: "Cancelled",
  },
  {
    orderId: "LFI-0269",
    shipmentId: "SH-4839239",
    guest: "Lily King",
    hotel: "Luxury Suites",
    courier: "FedEx",
    trackingNumber: "FED-2839239",
    labelStatus: "Label generated",
    shipmentStatus: "Delivered",
  },
  {
    orderId: "LFI-0270",
    shipmentId: "SH-4839240",
    guest: "Mason Scott",
    hotel: "Business Tower Hotel",
    courier: "UPS",
    trackingNumber: "UPS-3839240",
    labelStatus: "Label generated",
    shipmentStatus: "In transit",
  },
];
