export const webhookLogsData = [
  {
    eventId: "EV-0231",
    shipmentId: "SH-4839201",
    courier: "DHL",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "20/03/2025",
    labelStatus: "Label generated",
    message: "Location: Berlin\nStatus: Transit",
  },
  {
    eventId: "EV-0232",
    shipmentId: "SH-4839202",
    courier: "UPS",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "20/03/2025",
    labelStatus: "Label generated",
    message: "Location: Berlin\nStatus: Delivered",
  },
  {
    eventId: "EV-0233",
    shipmentId: "SH-4839203",
    courier: "UPS",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "20/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Berlin\nStatus: Transit",
  },
  {
    eventId: "EV-0234",
    shipmentId: "SH-4839204",
    courier: "UPS",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Failed",
    receivedAt: "20/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Berlin\nStatus: Transit",
  },
  {
    eventId: "EV-0235",
    shipmentId: "SH-4839205",
    courier: "FedEx",
    eventType: "Pending",
    httpStatus: "500",
    processingStatus: "Failed",
    receivedAt: "19/03/2025",
    labelStatus: "Label generated",
    message: "Location: Paris\nStatus: Pending",
  },
  {
    eventId: "EV-0236",
    shipmentId: "SH-4839206",
    courier: "DHL",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "19/03/2025",
    labelStatus: "Label generated",
    message: "Location: Rome\nStatus: Transit",
  },
  {
    eventId: "EV-0237",
    shipmentId: "SH-4839207",
    courier: "UPS",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "18/03/2025",
    labelStatus: "Label generated",
    message: "Location: Madrid\nStatus: Delivered",
  },
  {
    eventId: "EV-0238",
    shipmentId: "SH-4839208",
    courier: "FedEx",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "18/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Lisbon\nStatus: Transit",
  },
  {
    eventId: "EV-0239",
    shipmentId: "SH-4839209",
    courier: "DHL",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "17/03/2025",
    labelStatus: "Label generated",
    message: "Location: Vienna\nStatus: Transit",
  },
  {
    eventId: "EV-0240",
    shipmentId: "SH-4839210",
    courier: "UPS",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "17/03/2025",
    labelStatus: "Label generated",
    message: "Location: Zurich\nStatus: Delivered",
  },

  {
    eventId: "EV-0241",
    shipmentId: "SH-4839211",
    courier: "FedEx",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "16/03/2025",
    labelStatus: "Label generated",
    message: "Location: Barcelona\nStatus: Transit",
  },
  {
    eventId: "EV-0242",
    shipmentId: "SH-4839212",
    courier: "DHL",
    eventType: "Pending",
    httpStatus: "500",
    processingStatus: "Failed",
    receivedAt: "16/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Rome\nStatus: Pending",
  },
  {
    eventId: "EV-0243",
    shipmentId: "SH-4839213",
    courier: "UPS",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "15/03/2025",
    labelStatus: "Label generated",
    message: "Location: Paris\nStatus: Delivered",
  },
  {
    eventId: "EV-0244",
    shipmentId: "SH-4839214",
    courier: "FedEx",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "15/03/2025",
    labelStatus: "Label generated",
    message: "Location: Madrid\nStatus: Transit",
  },
  {
    eventId: "EV-0245",
    shipmentId: "SH-4839215",
    courier: "DHL",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "14/03/2025",
    labelStatus: "Label generated",
    message: "Location: Berlin\nStatus: Delivered",
  },
  {
    eventId: "EV-0246",
    shipmentId: "SH-4839216",
    courier: "UPS",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "14/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Lisbon\nStatus: Transit",
  },
  {
    eventId: "EV-0247",
    shipmentId: "SH-4839217",
    courier: "FedEx",
    eventType: "Pending",
    httpStatus: "500",
    processingStatus: "Failed",
    receivedAt: "13/03/2025",
    labelStatus: "Label generated",
    message: "Location: Vienna\nStatus: Pending",
  },
  {
    eventId: "EV-0248",
    shipmentId: "SH-4839218",
    courier: "DHL",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "13/03/2025",
    labelStatus: "Label generated",
    message: "Location: Zurich\nStatus: Transit",
  },
  {
    eventId: "EV-0249",
    shipmentId: "SH-4839219",
    courier: "UPS",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "12/03/2025",
    labelStatus: "Label generated",
    message: "Location: Rome\nStatus: Delivered",
  },
  {
    eventId: "EV-0250",
    shipmentId: "SH-4839220",
    courier: "FedEx",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "12/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Barcelona\nStatus: Transit",
  },

  {
    eventId: "EV-0251",
    shipmentId: "SH-4839221",
    courier: "DHL",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "11/03/2025",
    labelStatus: "Label generated",
    message: "Location: Madrid\nStatus: Transit",
  },
  {
    eventId: "EV-0252",
    shipmentId: "SH-4839222",
    courier: "UPS",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "11/03/2025",
    labelStatus: "Label generated",
    message: "Location: Vienna\nStatus: Delivered",
  },
  {
    eventId: "EV-0253",
    shipmentId: "SH-4839223",
    courier: "FedEx",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "10/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Berlin\nStatus: Transit",
  },
  {
    eventId: "EV-0254",
    shipmentId: "SH-4839224",
    courier: "DHL",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "10/03/2025",
    labelStatus: "Label generated",
    message: "Location: Lisbon\nStatus: Delivered",
  },
  {
    eventId: "EV-0255",
    shipmentId: "SH-4839225",
    courier: "UPS",
    eventType: "Pending",
    httpStatus: "500",
    processingStatus: "Failed",
    receivedAt: "09/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Rome\nStatus: Pending",
  },
  {
    eventId: "EV-0256",
    shipmentId: "SH-4839226",
    courier: "FedEx",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "09/03/2025",
    labelStatus: "Label generated",
    message: "Location: Paris\nStatus: Transit",
  },
  {
    eventId: "EV-0257",
    shipmentId: "SH-4839227",
    courier: "DHL",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "08/03/2025",
    labelStatus: "Label generated",
    message: "Location: Zurich\nStatus: Delivered",
  },
  {
    eventId: "EV-0258",
    shipmentId: "SH-4839228",
    courier: "UPS",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "08/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Berlin\nStatus: Transit",
  },
  {
    eventId: "EV-0259",
    shipmentId: "SH-4839229",
    courier: "FedEx",
    eventType: "Pending",
    httpStatus: "500",
    processingStatus: "Failed",
    receivedAt: "07/03/2025",
    labelStatus: "Label generated",
    message: "Location: Vienna\nStatus: Pending",
  },
  {
    eventId: "EV-0260",
    shipmentId: "SH-4839230",
    courier: "DHL",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "07/03/2025",
    labelStatus: "Label generated",
    message: "Location: Madrid\nStatus: Transit",
  },

  {
    eventId: "EV-0261",
    shipmentId: "SH-4839231",
    courier: "UPS",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "06/03/2025",
    labelStatus: "Label generated",
    message: "Location: Paris\nStatus: Delivered",
  },
  {
    eventId: "EV-0262",
    shipmentId: "SH-4839232",
    courier: "DHL",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "06/03/2025",
    labelStatus: "Label generated",
    message: "Location: Rome\nStatus: Transit",
  },
  {
    eventId: "EV-0263",
    shipmentId: "SH-4839233",
    courier: "FedEx",
    eventType: "Pending",
    httpStatus: "500",
    processingStatus: "Failed",
    receivedAt: "05/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Vienna\nStatus: Pending",
  },
  {
    eventId: "EV-0264",
    shipmentId: "SH-4839234",
    courier: "UPS",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "05/03/2025",
    labelStatus: "Label generated",
    message: "Location: Berlin\nStatus: Delivered",
  },
  {
    eventId: "EV-0265",
    shipmentId: "SH-4839235",
    courier: "DHL",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "04/03/2025",
    labelStatus: "Label generated",
    message: "Location: Zurich\nStatus: Transit",
  },
  {
    eventId: "EV-0266",
    shipmentId: "SH-4839236",
    courier: "FedEx",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "04/03/2025",
    labelStatus: "Label generated",
    message: "Location: Barcelona\nStatus: Delivered",
  },
  {
    eventId: "EV-0267",
    shipmentId: "SH-4839237",
    courier: "UPS",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "03/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Lisbon\nStatus: Transit",
  },
  {
    eventId: "EV-0268",
    shipmentId: "SH-4839238",
    courier: "DHL",
    eventType: "Pending",
    httpStatus: "500",
    processingStatus: "Failed",
    receivedAt: "03/03/2025",
    labelStatus: "Cancelled",
    message: "Location: Madrid\nStatus: Pending",
  },
  {
    eventId: "EV-0269",
    shipmentId: "SH-4839239",
    courier: "FedEx",
    eventType: "Delivered",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "02/03/2025",
    labelStatus: "Label generated",
    message: "Location: Rome\nStatus: Delivered",
  },
  {
    eventId: "EV-0270",
    shipmentId: "SH-4839240",
    courier: "UPS",
    eventType: "In transit",
    httpStatus: "200",
    processingStatus: "Processed",
    receivedAt: "02/03/2025",
    labelStatus: "Label generated",
    message: "Location: Paris\nStatus: Transit",
  },
];
